name: immutable
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.87064
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c8ceda'
    - '#592900'
    - '#00414f'
    - '#57798b'
  brandStrength: 0.875
  lightness: 0.3125
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
