name: immutable
favicon: null
layout_spectrum: 0.61153
typography_spectrum: 0.90076
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#29313e'
    - '#ffffff'
    - '#6d6f6c'
    - '#7c8999'
    - '#b6ba4a'
  brandStrength: 0.0625
  lightness: 0.1875
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
