name: immutable
favicon: null
layout_spectrum: 0.49819
typography_spectrum: 0.5150779732502997
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c8ceda'
    - '#592900'
    - '#00414f'
    - '#57798b'
  brandStrength: 0.5
  lightness: 0.701002785237506
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
