name: immutable
favicon: null
layout_spectrum: 0.61392
typography_spectrum: 0.93761
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#ffffff'
    - '#a2bdff'
    - '#b570ff'
    - '#6b30ff'
  brandStrength: 0.875
  lightness: 0.1875
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
