name: immutable
favicon: null
layout_spectrum: 0.61392
typography_spectrum: 0.93761
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2057d5'
    - '#040000'
    - '#fbf2f9'
    - '#b8b1af'
    - '#583136'
  brandStrength: 0.875
  lightness: 0.1875
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
