name: immutable
favicon: null
layout_spectrum: 0.60127
typography_spectrum: 0.93761
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#222631'
    - '#3d444e'
    - '#ffffff'
    - '#91919b'
    - '#d3c1ad'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
